# Generated by Django 3.1.13 on 2022-10-30 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_submitvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitvote',
            name='poll_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
