# Generated by Django 3.1.13 on 2022-10-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_submitvote_poll_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitvote',
            name='poll_id',
            field=models.CharField(max_length=500),
        ),
    ]
