# Generated by Django 3.1.13 on 2022-10-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20221030_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='classAno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='classBno',
            field=models.IntegerField(default=0),
        ),
    ]
