# Generated by Django 3.1.13 on 2022-10-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20221030_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitvote',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
